<link rel="stylesheet" href="{{asset('assets/css/bootstrap.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/animate.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/custom-animation.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/font-awesome-pro.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/swiper-bundle.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/slick.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/nice-select.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/spacing.css')}}">
<link rel="stylesheet" href="{{asset('assets/css/main.css')}}">